### ISSUE TITLE
Declare dependency on matplotlib

### ISSUE THREAD

**Issue by pganssle** [pganssle/grid-strategy#14]
We need to add an explicit dependency on `matplotlib` for now (we can drop it later if it becomes optional because we've added another plotting backend).

It should be added under `[options]` in `setup.cfg`, it is under the `install_requires` section.

**Comment by konoikon** [comment]
Do we care about the matplotlib version?

**Comment by pganssle** [comment]
@konoikon I don't think so. Once we have the tests ready to go if we want we can try out a bunch of old matplotlib versions and see if any of them fail, but for now we'll just do an unqualified dependency.
