### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by pganssle** [pganssle/grid-strategy#5]
Probably Azure Pipelines and/or Travis CI. See the [repos to steal from](https://github.com/pganssle/grid-strategy/wiki#repos-to-steal-from-learn-from) section - `tox`, `virtualenv` and `dateutil` all have strong Azure Pipelines pipelines, but note!

We only support Python >= 3.6, so we can get away with a much less elaborate set of pipelines and jobs. 3.6, 3.7 and 3.8-dev (allowed failure), on Linux, Mac and Windows I think should be sufficient.

**Comment by MorganHaworth** [comment]
Working on this
